[package]
name = "lang-java-parser"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
exclude = ["examples/ts-tree.rs"]

[lib]
name = "beans_lang_java_parser"

[dependencies]
lang-java-model = { path = "../model" }
tree-sitter.workspace = true
tree-sitter-java.workspace = true
