[package]
name = "beans-workspace-toml"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
beans-core.workspace = true
beans-workspace.workspace = true
log.workspace = true
serde.workspace = true
toml.workspace = true
url.workspace = true
