[workspace]
resolver = "3"
members = [
    "crates/core/engine",
    "crates/core/model",
    "crates/core/resolution",
    "crates/engine",
    "crates/lang/java/engine",
    "crates/lang/java/model",
    "crates/lang/java/resolution",
    "crates/lang/java/semantics",
    "crates/lang/java/server",
    "crates/lsp/models",
    "crates/lsp/server",
    "crates/platform/jvm/engine",
    "crates/platform/jvm/model",
    "crates/platform/jvm/semantics",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
authors = ["Bálint Hegyi <me@blnt.dev>"]
license = "Apache-2.0"

[workspace.dependencies]
blake3 = "1"
cafebabe = { version = "0.9", default-features = false }
lsp-server = "0.8"
lsp-types = "0.97"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.9"
tree-sitter = "0.25"
tree-sitter-java = "0.23"
