[package]
name = "platform-jvm-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "beans_platform_jvm_engine"

[dependencies]
core-engine = { path = "../../../core/engine" }
core-model = { path = "../../../core/model" }
platform-jvm-model = { path = "../model" }
platform-jvm-semantics = { path = "../semantics" }
