[package]
name = "platform-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "beans_platform_engine"

[dependencies]
core-engine = { path = "../../core/engine" }
core-model = { path = "../../core/model" }
platform-model = { path = "../model" }
