[package]
name = "lang-java-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "beans_lang_java_engine"

[dependencies]
core-engine = { path = "../../../core/engine" }
core-model = { path = "../../../core/model" }
core-resolution = { path = "../../../core/resolution" }
lang-java-model = { path = "../model" }
lang-java-semantics = { path = "../semantics" }

[dev-dependencies]
lang-java-resolution = { path = "../resolution" }
