[package]
name = "beans-lang-java"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
beans-core.workspace = true
beans-platform-jvm.workspace = true
tree-sitter.workspace = true
tree-sitter-java.workspace = true
url.workspace = true

[[example]]
name = "inspect"
path = "examples/inspection/inspect.rs"
