[package]
name = "platform-jvm-semantics"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "beans_platform_jvm_semantics"

[dependencies]
cafebabe.workspace = true
core-engine = { path = "../../../core/engine" }
core-model = { path = "../../../core/model" }
platform-jvm-model = { path = "../model" }
