[package]
name = "lang-java-resolution"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "beans_lang_java_resolution"

[dependencies]
core-engine = { path = "../../../core/engine" }
core-model = { path = "../../../core/model" }
core-resolution = { path = "../../../core/resolution" }
lang-java-model = { path = "../model" }
lang-java-semantics = { path = "../semantics" }
platform-jvm-model = { path = "../../../platform/jvm/model" }
platform-jvm-semantics = { path = "../../../platform/jvm/semantics" }
