[package]
name = "lang-java-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "beans_lang_java_server"

[dependencies]
lang-java-model = { path = "../model" }
lang-java-parser = { path = "../parser" }
lang-java-semantics = { path = "../semantics" }
lsp-types.workspace = true
