[package]
name = "beans-platform-jvm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
beans-core.workspace = true
beans-storage.workspace = true
cafebabe.workspace = true
zip.workspace = true

[dev-dependencies]
tempfile.workspace = true
